# Generated by Django 5.0.6 on 2025-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='until',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='bysetpos',
            new_name='weekday_ordinal',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='monthly_type',
            field=models.CharField(blank=True, choices=[('WEEKDAY', 'Weekday'), ('DATE', 'Date')], max_length=10, null=True),
        ),
    ]
